### ISSUE TITLE
cross compilation for powerpc: Elf parser traceback

### ISSUE THREAD

**Issue by anordal** [jpakkane/meson#108]
Testing out cross compilation for powerpc (e500v2). We are able to compile an executable, a static library and a shared library, but only the static library installs cleanly.

ninja install:
```
[1/1] Regenerating build files
The Meson build system
Version: 0.24.0-research
Source dir: /home/an/meson-ppc-reduced-tc
Build dir: /tmp/build-ppc


Build type: cross build
Project name: rather simple
Native c compiler: ccache cc (gcc 4.8.3)
Cross c compiler: /opt/x-tools/powerpc-e500v2-linux-gnuspe-4.7.2-2/bin/powerpc-e500v2-linux-gnuspe-gcc (gcc 4.7.2)
Build targets in project: 3
[7/7] Installing files.
Installing prog to /tmp/install/bin/prog
Could not fix dependency info.

Stdout:


Stderr:
Traceback (most recent call last):
  File "/usr/local/share/meson/depfixer.py", line 254, in <module>
    e = Elf(sys.argv[1])
  File "/usr/local/share/meson/depfixer.py", line 106, in __init__
    self.parse_sections()
  File "/usr/local/share/meson/depfixer.py", line 142, in parse_sections
    self.sections.append(SectionHeader(self.bf, self.ptrsize))
  File "/usr/local/share/meson/depfixer.py", line 66, in __init__
    self.sh_name = struct.unpack(self.Word, ifile.read(self.WordSize))[0];
struct.error: unpack requires a bytes object of length 4


FAILED: '/usr/bin/python3' '/usr/local/share/meson/meson_install.py' '/tmp/build-ppc/meson-private/install.dat'
ninja: build stopped: subcommand failed.
```

Cross file:
```
name = 'linux'
c = '/opt/x-tools/powerpc-e500v2-linux-gnuspe-4.7.2-2/bin/powerpc-e500v2-linux-gnuspe-gcc'
cpp = '/opt/x-tools/powerpc-e500v2-linux-gnuspe-4.7.2-2/bin/powerpc-e500v2-linux-gnuspe-g++'
ar = '/opt/x-tools/powerpc-e500v2-linux-gnuspe-4.7.2-2/bin/powerpc-e500v2-linux-gnuspe-ar'
strip = '/opt/x-tools/powerpc-e500v2-linux-gnuspe-4.7.2-2/bin/powerpc-e500v2-linux-gnuspe-strip'

sizeof_int = 4
sizeof_wchar_t = 4
sizeof_void* = 4

alignment_char = 1
alignment_void* = 4
alignment_double = 8

has_function_printf = true
```

The sizes and alignments were found experimentally, by running a program on the target architecture that prints them. This is based on the "Linux ARM" example from the "Cross compilation" wiki page. Something else needed?

And the meson.build:
```
project('rather simple', 'c')

shared = shared_library(
  'shared',
  sources : 'main.c',
  install : true)

static = static_library(
  'static',
  sources : 'main.c',
  install : true)

prog = executable(
  'prog',
  sources : 'main.c',
  install : true)
```

main.c is as simple as it gets:
```
int main() {
  return 3;
}
```

The whole project, with the built binaries: [meson-ppc-reduced-tc.tar.gz](http://nerdvar.com/ting/meson-ppc-reduced-tc.tar.gz)

Looking at the traces from meson, it looks like the parsing of ELF section headers is what fails. We have tested that both readelf and the [pyelftools](https://github.com/eliben/pyelftools) library are able to parse and print out the section headers of all generated binaries.

**Comment by jpakkane** [comment]
This was an endianness bug in the elf parser. I have pushed a fix, can you please test it again?

**Comment by anordal** [comment]
Thanks! Will test again monday morning.

**Comment by anordal** [comment]
Yes, that was it.
Thank you very much for the quick fix, and an awesome build system!
