### ISSUE TITLE
TypeError: Can't convert 'File' object to str implicitly

### ISSUE THREAD

**Issue by ignatenkobrain** [jpakkane/meson#118]
```
The Meson build system
Version: 0.24.0-research
Source dir: /home/brain/git/gnome-tasks
Build dir: /home/brain/git/gnome-tasks/build
Build type: native build
Project name: gnome-tasks
warning: --output and -o have no effect when -C or --ccode is set
Compilation succeeded - 1 warning(s)
Native vala compiler: valac (unknown 0.28.0)
Native c compiler: ccache cc (gcc 5.1.1)
Found pkg-config: /usr/bin/pkg-config (0.28)
Dependency glib-2.0 found: YES 2.45.1
Build targets in project: 1
Traceback (most recent call last):
  File "/home/brain/git/meson/meson.py", line 188, in run
    app.generate()
  File "/home/brain/git/meson/meson.py", line 141, in generate
    g.generate()
  File "/home/brain/git/meson/ninjabackend.py", line 132, in generate
    [self.generate_target(t, outfile) for t in self.build.get_targets().values()]
  File "/home/brain/git/meson/ninjabackend.py", line 132, in <listcomp>
    [self.generate_target(t, outfile) for t in self.build.get_targets().values()]
  File "/home/brain/git/meson/ninjabackend.py", line 256, in generate_target
    obj_list.append(self.generate_single_compile(target, outfile, src, False, [], header_deps))
  File "/home/brain/git/meson/ninjabackend.py", line 1087, in generate_single_compile
    compiler = self.get_compiler_for_source(src)
  File "/home/brain/git/meson/backends.py", line 56, in get_compiler_for_source
    raise RuntimeError('No specified compiler can handle file ' + src)
TypeError: Can't convert 'File' object to str implicitly
```

**Comment by ignatenkobrain** [comment]
again, my fail

**Comment by robertsanseries** [comment]
@ignatenkobrain how to solve?

**Comment by nirbheek** [comment]
That traceback applies to an ancient version of meson, and the problem is almost certainly not the same that you are facing. Please file a new bug with details. Thanks!

**Comment by robertsanseries** [comment]
@nirbheek ok! thanks.
