### ISSUE TITLE
AttributeError: 'ValaCompiler' object has no attribute 'get_always_args'

### ISSUE THREAD

**Issue by ignatenkobrain** [jpakkane/meson#119]
```
Traceback (most recent call last):
  File "/home/brain/git/meson/meson.py", line 188, in run
    app.generate()
  File "/home/brain/git/meson/meson.py", line 141, in generate
    g.generate()
  File "/home/brain/git/meson/ninjabackend.py", line 132, in generate
    [self.generate_target(t, outfile) for t in self.build.get_targets().values()]
  File "/home/brain/git/meson/ninjabackend.py", line 132, in <listcomp>
    [self.generate_target(t, outfile) for t in self.build.get_targets().values()]
  File "/home/brain/git/meson/ninjabackend.py", line 256, in generate_target
    obj_list.append(self.generate_single_compile(target, outfile, src, False, [], header_deps))
  File "/home/brain/git/meson/ninjabackend.py", line 1088, in generate_single_compile
    commands = self.generate_basic_compiler_args(target, compiler)
  File "/home/brain/git/meson/backends.py", line 193, in generate_basic_compiler_args
    commands += compiler.get_always_args()
AttributeError: 'ValaCompiler' object has no attribute 'get_always_args'
```

**Comment by ignatenkobrain** [comment]
The same for buildtype, include and some more flags

**Comment by ignatenkobrain** [comment]
my fail
