### ISSUE TITLE
test/objc: required program gnustep-config

### ISSUE THREAD

**Issue by ignatenkobrain** [jpakkane/meson#42]
```
Traceback (most recent call last):
  File "./meson.py", line 184, in <module>
    app.generate()
  File "./meson.py", line 135, in generate
    intr.run()
  File "/builddir/build/BUILD/meson-c6dbf98a055bb0fe1d36fc9f4f757b67ca613f01/interpreter.py", line 762, in run
    self.evaluate_codeblock(self.ast)
  File "/builddir/build/BUILD/meson-c6dbf98a055bb0fe1d36fc9f4f757b67ca613f01/interpreter.py", line 784, in evaluate_codeblock
    raise e
  File "/builddir/build/BUILD/meson-c6dbf98a055bb0fe1d36fc9f4f757b67ca613f01/interpreter.py", line 778, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/builddir/build/BUILD/meson-c6dbf98a055bb0fe1d36fc9f4f757b67ca613f01/interpreter.py", line 826, in evaluate_statement
    return self.evaluate_if(cur)
  File "/builddir/build/BUILD/meson-c6dbf98a055bb0fe1d36fc9f4f757b67ca613f01/interpreter.py", line 1578, in evaluate_if
    self.evaluate_codeblock(node.elseblock)
  File "/builddir/build/BUILD/meson-c6dbf98a055bb0fe1d36fc9f4f757b67ca613f01/interpreter.py", line 784, in evaluate_codeblock
    raise e
  File "/builddir/build/BUILD/meson-c6dbf98a055bb0fe1d36fc9f4f757b67ca613f01/interpreter.py", line 778, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/builddir/build/BUILD/meson-c6dbf98a055bb0fe1d36fc9f4f757b67ca613f01/interpreter.py", line 818, in evaluate_statement
    return self.assignment(cur)
  File "/builddir/build/BUILD/meson-c6dbf98a055bb0fe1d36fc9f4f757b67ca613f01/interpreter.py", line 1460, in assignment
    value = self.evaluate_statement(node.value)
  File "/builddir/build/BUILD/meson-c6dbf98a055bb0fe1d36fc9f4f757b67ca613f01/interpreter.py", line 816, in evaluate_statement
    return self.function_call(cur)
  File "/builddir/build/BUILD/meson-c6dbf98a055bb0fe1d36fc9f4f757b67ca613f01/interpreter.py", line 1442, in function_call
    return self.funcs[func_name](node, posargs, kwargs)
  File "/builddir/build/BUILD/meson-c6dbf98a055bb0fe1d36fc9f4f757b67ca613f01/interpreter.py", line 1122, in func_dependency
    dep = dependencies.find_external_dependency(name, kwargs)
  File "/builddir/build/BUILD/meson-c6dbf98a055bb0fe1d36fc9f4f757b67ca613f01/dependencies.py", line 802, in find_external_dependency
    dep = packages[name](kwargs)
  File "/builddir/build/BUILD/meson-c6dbf98a055bb0fe1d36fc9f4f757b67ca613f01/dependencies.py", line 672, in __init__
    self.detect()
  File "/builddir/build/BUILD/meson-c6dbf98a055bb0fe1d36fc9f4f757b67ca613f01/dependencies.py", line 677, in detect
    stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib64/python3.4/subprocess.py", line 858, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.4/subprocess.py", line 1456, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'gnustep-config'
```

**Comment by jpakkane** [comment]
I have fixed the error handling. To build gnustep programs you need to install gnustep-config and gnustep-base-devel.
