### ISSUE TITLE
introspect: AttributeError: 'list' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by ignatenkobrain** [jpakkane/meson#50]
```python
$ ./mesonintrospect.py --targets /home/brain/git/GNOME/gnome-keysign/build
Traceback (most recent call last):
  File "./mesonintrospect.py", line 160, in <module>
    list_targets(coredata, builddata)
  File "./mesonintrospect.py", line 47, in list_targets
    t['filename'] = os.path.join(target.subdir, target.get_filename())
  File "/usr/lib64/python3.4/posixpath.py", line 79, in join
    if b.startswith(sep):
AttributeError: 'list' object has no attribute 'startswith'
```

**Comment by ignatenkobrain** [comment]
```python
>>> [x.get_filename() for x in builddata.get_targets().values()]
['libkeysign.a', ['gks-resources.c'], 'gnome-keysign', ['gks-resources.h']]
```

**Comment by ignatenkobrain** [comment]
This is what I have in `meson.build`. This is caused by module `gnome.compile_resources()`
```
resources = gnome.compile_resources('gks-resources',
                                    'gnome-keysign.gresource.xml',
                                    source_dir : 'data',
                                    c_name : 'gks')
```
