### ISSUE TITLE
CI: don't have permissions to se statuses for commits/pull requests

### ISSUE THREAD

**Issue by ignatenkobrain** [jpakkane/meson#73]
http://vm666.clanwars.org/job/meson/11/console
```java
Setting status of 3be7297de8d6c72b36911e0108759d2b66df77f6 to PENDING with url http://vm666.clanwars.org/job/meson/11/ and message: Merged build started.
FileNotFoundException means that the credentials Jenkins is using is probably wrong. Or that something is really wrong with github.
java.io.FileNotFoundException: https://api.github.com/repos/jpakkane/meson/statuses/3be7297de8d6c72b36911e0108759d2b66df77f6
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1835)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at org.kohsuke.github.Requester.parse(Requester.java:396)
	at org.kohsuke.github.Requester._to(Requester.java:198)
	at org.kohsuke.github.Requester.to(Requester.java:173)
	at org.kohsuke.github.GHRepository.createCommitStatus(GHRepository.java:731)
	at org.kohsuke.github.GHRepository.createCommitStatus(GHRepository.java:743)
	at org.jenkinsci.plugins.ghprb.GhprbRepository.createCommitStatus(GhprbRepository.java:140)
	at org.jenkinsci.plugins.ghprb.GhprbRepository.createCommitStatus(GhprbRepository.java:122)
	at org.jenkinsci.plugins.ghprb.GhprbBuilds.onStarted(GhprbBuilds.java:81)
	at org.jenkinsci.plugins.ghprb.GhprbBuildListener.onStarted(GhprbBuildListener.java:19)
	at org.jenkinsci.plugins.ghprb.GhprbBuildListener.onStarted(GhprbBuildListener.java:12)
	at hudson.model.listeners.RunListener.fireStarted(RunListener.java:213)
	at hudson.model.Run.execute(Run.java:1755)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:89)
	at hudson.model.Executor.run(Executor.java:240)
```

**Comment by ignatenkobrain** [comment]
We have 2 choices:
* Give me rw to repository to allow set flags for commits
* Give me you generated API key which has perms to set statuses.

**Comment by ignatenkobrain** [comment]
@jpakkane how we will deal?

**Comment by jpakkane** [comment]
I have never done API keys for github. Are there docs on how to do that?

**Comment by ignatenkobrain** [comment]
@jpakkane You need to open https://github.com/settings/applications
and create personal access token for `repo`, `repo:status` as minimal.

http://stackoverflow.com/questions/14274293/show-current-state-of-jenkins-build-on-github-repo/26910986#26910986
I will set up account for you in jenkins so you can install this token without me.
