### ISSUE TITLE
tests() and find_prog()

### ISSUE THREAD

**Issue by ignatenkobrain** [jpakkane/meson#91]
```
Traceback (most recent call last):
  File "/home/brain/git/upstream/meson/meson_test.py", line 176, in <module>
    run_tests(options, datafile)
  File "/home/brain/git/upstream/meson/meson_test.py", line 165, in run_tests
    drain_futures(futures)
  File "/home/brain/git/upstream/meson/meson_test.py", line 125, in drain_futures
    print_stats(numlen, tests, name, result.result(), i, logfile, jsonlogfile)
  File "/usr/lib64/python3.4/concurrent/futures/_base.py", line 402, in result
    return self.__get_result()
  File "/usr/lib64/python3.4/concurrent/futures/_base.py", line 354, in __get_result
    raise self._exception
  File "/usr/lib64/python3.4/concurrent/futures/thread.py", line 54, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/brain/git/upstream/meson/meson_test.py", line 96, in run_single_test
    env=child_env)
  File "/usr/lib64/python3.4/subprocess.py", line 858, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.4/subprocess.py", line 1456, in _execute_child
    raise child_exception_type(errno_num, err_msg)
OSError: [Errno 8] Exec format error
FAILED: '/usr/bin/python3' '/home/brain/git/upstream/meson/meson_test.py' '/home/brain/tmp/json-parser/buil/meson-private/meson_test_setup.dat'
ninja: build stopped: subcommand failed.
```

**Comment by jpakkane** [comment]
I've never seen an exec format error before. Some googling says that it is caused by trying to run a binary with the wrong architecture (e.g. 64 bit exe on 32 bit os). Can you verify that the binary it finds is the correct one and runnable and that if it is a script that its shebang line is correct?

**Comment by ignatenkobrain** [comment]
Binary is python file. I'll check shebang tomorrow

**Comment by ignatenkobrain** [comment]
it was wrong shebang, so closing it
